// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQoHQoUKIWqh7hqqwMxbWJu4XPGNG3uE',
    appId: '1:79692474995:web:f1721abe514f373d485806',
    messagingSenderId: '79692474995',
    projectId: 'laptrinh-dnt',
    authDomain: 'laptrinh-dnt.firebaseapp.com',
    storageBucket: 'laptrinh-dnt.firebasestorage.app',
    measurementId: 'G-7P8T6KJDLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPRkA2PwWbxmOfFjke_glv3_sS9k7he40',
    appId: '1:79692474995:android:5a2fb72f118cd59b485806',
    messagingSenderId: '79692474995',
    projectId: 'laptrinh-dnt',
    storageBucket: 'laptrinh-dnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79p4AVbAV_57TDC5yhzp5dooe89R6AAA',
    appId: '1:79692474995:ios:9e8a80b1f1e2e7a4485806',
    messagingSenderId: '79692474995',
    projectId: 'laptrinh-dnt',
    storageBucket: 'laptrinh-dnt.firebasestorage.app',
    iosBundleId: 'com.example.sharepreferences',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA79p4AVbAV_57TDC5yhzp5dooe89R6AAA',
    appId: '1:79692474995:ios:9e8a80b1f1e2e7a4485806',
    messagingSenderId: '79692474995',
    projectId: 'laptrinh-dnt',
    storageBucket: 'laptrinh-dnt.firebasestorage.app',
    iosBundleId: 'com.example.sharepreferences',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTQoHQoUKIWqh7hqqwMxbWJu4XPGNG3uE',
    appId: '1:79692474995:web:f3190f6ec370c86c485806',
    messagingSenderId: '79692474995',
    projectId: 'laptrinh-dnt',
    authDomain: 'laptrinh-dnt.firebaseapp.com',
    storageBucket: 'laptrinh-dnt.firebasestorage.app',
    measurementId: 'G-4QDBZ77GJD',
  );
}
